spring:
    datasource:
        driverClassName: org.h2.Driver
        url: jdbc:h2:mem:dbdev;
        username: sa
        password: sa
    h2:
        console:
            enabled: true
    jpa:
        defer-datasource-initialization: true
info:
    profile: Developer