openapi: 3.0.0
info:
  title: User Service for Store
  version: 1.0.0
  description: Documentation for the store's user service. Find the source code on [GitHub](https://github.com/rafaelnieto96/gft-users/)
tags:
  - name: Management
    description: User management operations
  - name: Search
    description: User search operations
  - name: Favorites
    description: User favorites management operations
paths:
  /users:
    post:
      summary: User creation
      tags:
        - Management
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                last_name:
                  type: string
                address:
                  type: string
                payment_method:
                  type: string
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              example:
                message: "User created successfully"
                id: 123

  /users/{id}:
    put:
      summary: Update user by ID
      tags:
        - Management
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                last_name:
                  type: string
                address:
                  type: string
                payment_method:
                  type: string
      responses:
        '200':
          description: User updated successfully
          content:
            application/json:
              example:
                message: "User updated successfully"

    delete:
      summary: Delete user by ID
      tags:
        - Management
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: User deleted successfully

    get:
      summary: Search user by ID
      tags:
        - Search
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Data of the requested user
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  last_name:
                    type: string
                  address:
                    type: string
                  payment_method:
                    type: string
                  id:
                    type: integer
                  loyalty_points:
                    type: integer
                  average_purchase:
                    type: number
                example:
                  name: "Juan"
                  last_name: "Pérez"
                  address: "Street 123"
                  payment_method: "Visa"
                  id: 456
                  loyalty_points: 20
                  average_purchase: 50.0

  /users/search:
    get:
      summary: Search user by name
      tags:
        - Search
      parameters:
        - in: query
          name: name
          required: true
          schema:
            type: string
      responses:
        '200':
          description: List of users matching the name
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    last_name:
                      type: string
                    address:
                      type: string
                    payment_method:
                      type: string
                    id:
                      type: integer
                    loyalty_points:
                      type: integer
                    average_purchase:
                      type: number
                example:
                  - name: "Ana"
                    last_name: "García"
                    address: "Avenue 456"
                    payment_method: "Paypal"
                    id: 789
                    loyalty_points: 30
                    average_purchase: 40.0
                  - name: "Juan"
                    last_name: "Pérez"
                    address: "Street 123"
                    payment_method: "Visa"
                    id: 456
                    loyalty_points: 20
                    average_purchase: 50.0

  /users/list:
    get:
      summary: List all users
      tags:
        - Search
      responses:
        '200':
          description: List of all users
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    last_name:
                      type: string
                    address:
                      type: string
                    payment_method:
                      type: string
                    id:
                      type: integer
                    loyalty_points:
                      type: integer
                    average_purchase:
                      type: number
                example:
                  - name: "Ana"
                    last_name: "García"
                    address: "Avenue 456"
                    payment_method: "Paypal"
                    id: 789
                    loyalty_points: 30
                    average_purchase: 40.0
                  - name: "Juan"
                    last_name: "Pérez"
                    address: "Street 123"
                    payment_method: "Visa"
                    id: 456
                    loyalty_points: 20
                    average_purchase: 50.0

  /users/upload:
    post:
      summary: Upload list of users
      tags:
        - Search
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  name:
                    type: string
                  last_name:
                    type: string
                  address:
                    type: string
                  payment_method:
                    type: string
      responses:
        '201':
          description: List of users uploaded successfully
          content:
            application/json:
              example:
                message: "List of users uploaded successfully"

  /users/favorite:
    post:
      summary: Add favorite
      tags:
        - Favorites
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                product_id:
                  type: integer
      responses:
        '201':
          description: Favorite added successfully
          content:
            application/json:
              example:
                message: "Favorite added successfully"

    delete:
      summary: Delete favorite
      tags:
        - Favorites
      parameters:
        - in: query
          name: user_id
          required: true
          schema:
            type: integer
        - in: query
          name: product_id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Favorite deleted successfully
