openapi: 3.1.0
info:
  title: userAPI
  description: API documentation for users and favorites
  version: 1.0.0
servers:
  - url: http://localhost:8085/
    description: Testing Server
externalDocs:
  description: Repository on GitHub
  url: 'https://github.com/tuusuario/turepositorio'
tags:
  - name: Management
    description: User management operations
  - name: Search
    description: User search operations
  - name: Favorites
    description: User favorites management operations
paths:
  /users:
    post:
      summary: Create a new user
      tags:
        - Management
      requestBody:
        content:
          application/json:
            example:
              name: John
              lastName: Doe
              street: Main St
              city: City
              province: Province
              postalCode: 12345
              country: Spain
              paymentMethod: Credit Card
              fidelityPoints: 10
              averagePurchase: 50.0
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              example:
                id: 1
                name: John
                lastName: Doe
                address:
                  street: Main St
                  city: City
                  province: Province
                  postalCode: 12345
                  country: Spain
                paymentMethod: Credit Card
                fidelityPoints: 10
                averagePurchase: 50.0
        '400':
          description: Bad request
        '500':
          description: Internal Server Error

    get:
      summary: Get a list of all users
      tags:
        - Search
      responses:
        '200':
          description: List of users
          content:
            application/json:
              example:
                - id: 1
                  name: John
                  lastName: Doe
                  address:
                    street: Main St
                    city: City
                    province: Province
                    postalCode: 12345
                    country: Spain
                  paymentMethod: Credit Card
                  fidelityPoints: 10
                  averagePurchase: 50.0
        '500':
          description: Internal Server Error

  /users/{id}:
    get:
      summary: Get user by ID
      tags:
        - Search
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: User details
          content:
            application/json:
              example:
                id: 1
                name: John
                lastName: Doe
                address:
                  street: Main St
                  city: City
                  province: Province
                  postalCode: 12345
                  country: Spain
                paymentMethod: Credit Card
                fidelityPoints: 10
                averagePurchase: 50.0
        '404':
          description: User not found
        '500':
          description: Internal Server Error

    put:
      summary: Update user by ID
      tags:
        - Management
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            example:
              name: John
              lastName: Doe
              street: Updated St
              city: Updated City
              province: Updated Province
              postalCode: 54321
              country: Estonia
              paymentMethod: PayPal
              fidelityPoints: 20
              averagePurchase: 75.0
      responses:
        '200':
          description: User updated successfully
          content:
            application/json:
              example:
                id: 1
                name: John
                lastName: Doe
                address:
                  street: Updated St
                  city: Updated City
                  province: Updated Province
                  postalCode: 54321
                  country: Estonia
                paymentMethod: PayPal
                fidelityPoints: 20
                averagePurchase: 75.0
        '404':
          description: User not found
        '500':
          description: Internal Server Error

    delete:
      summary: Delete user by ID
      tags:
        - Management
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: User deleted successfully
        '404':
          description: User not found
        '500':
          description: Internal Server Error

  /users/{id}/fidelity-points:
    get:
      summary: Update user fidelity points by ID
      tags:
        - Management
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: User fidelity points updated successfully
          content:
            application/json:
              example:
                id: 1
                name: John
                fidelityPoints: 50
        '404':
          description: User not found
        '500':
          description: Internal Server Error

  /favorites:
    post:
      summary: Add a favorite product
      tags:
        - Favorites
      requestBody:
        content:
          application/json:
            example:
              user: 1
              product: 101
      responses:
        '201':
          description: Favorite added successfully
          content:
            application/json:
              example:
                user: 1
                product: 101
        '400':
          description: Bad request
        '404':
          description: User not found
        '500':
          description: Internal Server Error

    delete:
      summary: Delete a favorite product
      tags:
        - Favorites
      requestBody:
        content:
          application/json:
            example:
              user: 1
              product: 101
      responses:
        '200':
          description: Favorite deleted successfully
        '400':
          description: Bad request
        '404':
          description: Favorite not found
        '500':
          description: Internal Server Error

  /favorites/user/{id}:
    get:
      summary: Search favorites for a user
      tags:
        - Favorites
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: User favorites
          content:
            application/json:
              example:
                user:
                  id: 1
                  name: John
                favorites:
                  - 101
                  - 102
        '404':
          description: User not found
        '500':
          description: Internal Server Error
